---
title: "Dados ambientais de Salvador"
output: 
  flexdashboard::flex_dashboard:
    css: style.css
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
# Library
library(dygraphs)
library(xts)          # To make the convertion data-frame / xts format
library(tidyverse)
library(lubridate)
library(readr)
dados <- read_delim("data/32497_.csv",
     ";", escape_double = FALSE, col_types =
       cols(DataHora_GMT = col_datetime(format = "%Y-%m-%d %H:%M:%S"),
         CorrPSol_Logico = col_integer()),
     trim_ws = TRUE)
```



### Chart A

```{r ,eval=TRUE, echo=FALSE}
#data$datetime <- ymd_hms(data$datetime)
# Then you can create the xts necessary to use dygraph
don <- xts(x = dados$`RadSolAcum _Mjm-2`, order.by = dados$DataHora_GMT)

# Finally the plot
dygraph(don) %>%
  dyOptions(labelsUTC = TRUE, fillGraph=TRUE, fillAlpha=0.2, drawGrid = FALSE, colors="#fed26e") %>%
  dyRangeSelector() %>%
  dyCrosshair(direction = "vertical") %>%
  dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)  %>%
  dyRoller(rollPeriod = 1) %>% dyCSS("dygraph.css")

# save the widget
# library(htmlwidgets)
# saveWidget(p, file=paste0( getwd(), "/HtmlWidget/dygraphs318.html"))
```
